###
GET http://localhost:8080/autos

###
GET http://localhost:8080/autos/toyota

###
GET http://localhost:8080/autos/toyota/yaris

###
POST http://localhost:8080/autos HTTP/1.1
content-type: application/json

{
    "merk": "kia",
    "model": "rio",
    "specs": {"uitvoering": "elektrisch", "carrosserie": "sedan"}
}

###
PATCH  http://localhost:8080/autos/kia/rio HTTP/1.1
content-type: application/json

{
    "uitvoering": "elektrisch",
    "versnelling": "coupe"
}

###
DELETE  http://localhost:8080/autos/kia

###
DELETE  http://localhost:8080/autos/kia/rio

###
DELETE  http://localhost:8080/autos/kia/rio/uitvoering

