###
GET https://autokeuzehulp.onrender.com/testkeuzes

###
DELETE  https://autokeuzehulp.onrender.com/testkeuzes/uitvoering

// favmerken    onfavmerken     uitvoering(+versnelling)      soortautos    gebruik   interesses

