###
GET https://autokeuzehulp.onrender.com/testkeuzes

###
DELETE  https://autokeuzehulp.onrender.com/testkeuzes/interesses

// favmerken    onfavmerken     uitvoeringen      soortautos    gebruik   interesses

