###
GET https://autokeuzehulp.onrender.com/testkeuzes

###
DELETE  https://autokeuzehulp.onrender.com/testkeuzes/favmerken

// favmerken    onfavmerken     uitvoering(+versnelling)      soortautos    gebruik   interesses

###
POST https://autokeuzehulp.onrender.com/testkeuzes HTTP/1.1
content-type: application/json

{
   "favmerken" : ["toyota", "kia", "volkswagen"]

}